item {
  id: 1
  name: 'Onion'
}

item {
  id: 2
  name: 'beet'
}

item {
  id: 3
  name: 'bell_pepper'
}

item {
  id: 4
  name: 'cabbage'
}

item {
  id: 5
  name: 'carrot'
}

item {
  id: 6
  name: 'cucumber'
}

item {
  id: 7
  name: 'egg'
}

item {
  id: 8
  name: 'eggplant'
}

item {
  id: 9
  name: 'garlic'
}

item {
  id: 10
  name: 'green_pepper'
}

item {
  id: 11
  name: 'haft-cabbage'
}

item {
  id: 12
  name: 'half onion'
}

item {
  id: 13
  name: 'onion'
}

item {
  id: 14
  name: 'potato'
}

item {
  id: 15
  name: 'tomato'
}

item {
  id: 16
  name: 'zucchini'
}

